// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD5yCwUOoSO6ZkqGtG4keTgQkT6kn3ygE',
    appId: '1:594151975677:web:55ecdbedb4317ce5f96c94',
    messagingSenderId: '594151975677',
    projectId: 'diasole-smartshoe',
    authDomain: 'diasole-smartshoe.firebaseapp.com',
    databaseURL: 'https://diasole-smartshoe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diasole-smartshoe.firebasestorage.app',
    measurementId: 'G-N84XPVT7M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm9JsuN3BhniJI4QFFbyN76HPzgmCzNCM',
    appId: '1:594151975677:android:f83d8abd101f2458f96c94',
    messagingSenderId: '594151975677',
    projectId: 'diasole-smartshoe',
    databaseURL: 'https://diasole-smartshoe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diasole-smartshoe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH47wa6o1N7kVuwgpWxrmPnA9p0-ks-eA',
    appId: '1:594151975677:ios:eded52b258fb6546f96c94',
    messagingSenderId: '594151975677',
    projectId: 'diasole-smartshoe',
    databaseURL: 'https://diasole-smartshoe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diasole-smartshoe.firebasestorage.app',
    iosBundleId: 'com.diasole.diasole',
  );
}
